class ApiConfig{
  static const String baseUrl= "https://api.themoviedb.org/3";
  static const String apitoken="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNDA0Y2NlZmRjZjY0MjU4ZTlkZjcyMTg2MDM2YmUzMSIsIm5iZiI6MTczODA5NjkzNS42NDMwMDAxLCJzdWIiOiI2Nzk5NDEyNzNhNzJiMjViNjQyYWViNGUiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.jJAoe_avITaRioxOEZc-koMz-VMZMGuXEs6msZu5xd4";
}